# 設定


theme:

  main:
    contents: 挑戦する勇気が未来を切り開く
    gist:
      失敗の痛み
      失敗してもいい
        失敗しても人の価値は失われない => ヒロインによる肯定
        挑戦することそのものが未来を作る => 挑戦することで自分が変わる、見える世界が変わる
      成功がもたらすよりよい明日

  sub:
    contents: 過程を楽しもう
    gist:
      苦しいときもあるがそこを脱すれば充実して感じられる
      挑戦している今このときを大切にする
      => 今に満足できることが重要

intention:
  1. 大小の課題を解決していく面白さを読者に提供する
  2. 主人公は武力において最強だが他の物事で苦労する
